apiVersion: v2
name: vscode-python
description: Minimal VS Code med Python. Brukeren kan selv installere pakker etter behov.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
  - VSCode
  - Python
home: https://manual.dapla.ssb.no/statistikkere/vscode-python.html
sources:
  - https://github.com/statisticsnorway/dapla-lab-images
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-library
type: application
version: 0.17.6
dependencies:
  - name: library-chart
    version: 4.5.0
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-library
