apiVersion: v2
name: jdemetra
description: Verkt√∏y for sesongjustering og tidsserie-analyse utviklet i samarbeid med Eurostat.
icon: https://avatars.githubusercontent.com/u/10142886
keywords:
  - JDemetra
home: https://manual.dapla.ssb.no/statistikkere/jdemetra.html
sources:
  - https://github.com/statisticsnorway/dapla-lab-images
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-standard
type: application
version: 1.7.6
dependencies:
  - name: library-chart
    version: 4.5.0
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-library
