apiVersion: v2
name: marimo
description: Marimo med Python.
icon: https://raw.githubusercontent.com/marimo-team/marimo/main/docs/_static/marimo-logotype-thick.svg
keywords:
  - Marimo
  - Python
home: https://manual.dapla.ssb.no/statistikkere/marimo.html
sources:
  - https://github.com/statisticsnorway/dapla-lab-images
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-library
type: application
version: 0.0.2
dependencies:
  - name: library-chart
    version: 4.4.9
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-library
