global:
  suspend: false
tjeneste:
  version: latest
  image:
    pullPolicy: IfNotPresent
  githubRepo: ''
  marimoAppFile: ''
security:
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
  serviceEntry:
    enabled: true
    hosts:
      - storage.googleapis.com
  oauth2:
    provider: keycloak-oidc
    oidcIssuerUrl: overwritten-by-onyxia
    clientId: my-client
    authenticatedEmails: ''
init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
  regionInitCheckSum: ''
userAttributes:
  environmentVariableName: OIDC_TOKEN
  userAttribute: access_token
  value: ''
oidc:
  enabled: true
  tokenExchangeUrl: ''
  secretName: ''
gitConfig:
  git:
    enabled: false
    configMapName: ''
    name: ''
    email: ''
    cache: ''
  github:
    token: ''
repository:
  configMapName: ''
  pipRepository: ''
  condaRepository: ''
replicaCount: 1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
environment:
  user: onyxia
  group: users
kubernetes:
  enabled: true
podAnnotations: {}
podSecurityContext:
  fsGroup: 100
securityContext: {}
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8080
istio:
  enabled: false
  gateways:
    - istio-namespace/example-gateway
  hostname: chart-example.local
resources:
  cpu: '200m'
  memory: '4Gi'
diskplass:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
userPreferences: {}
affinity: {}
dapla:
  sourceData:
    reason: ''
    requestedDuration: 4h
  group: dapla-felles-developers
  sharedBuckets: []
avansert:
  data:
    mountStandard: true
  startupScript:
    scriptPath: ''
    scriptArgs: ''
deleteJob:
  enabled: true
  cronMinuteAtDay: '0'
  cronHourAtDay: '20'
  imageVersion: v1.1.0
  clusterRoleName: onyxia-delete-job
  serviceAccount:
    annotations: {}
podDisruptionBudget:
  enabled: true
deployEnvironment: DEV
daplaUser: ''
statbankBaseUrl: ''
statbankEncryptUrl: ''
statbankTestBaseUrl: ''
statbankTestEncryptUrl: ''
suvDaplaApiUrl: ''
pseudoServiceUrl: ''
whodatServiceUrl: ''
maskinportenGuardianUrl: ''
