apiVersion: v2
name: rstudio
description: Minimal RStudio med R. Brukeren kan selv installere pakker.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/rstudio.png
keywords:
  - RStudio
  - R
home: https://manual.dapla.ssb.no/statistikkere/rstudio.html
sources:
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-standard-test
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-library
  - https://github.com/statisticsnorway/dapla-lab-images
type: application
version: 0.15.5
dependencies:
  - name: library-chart
    version: 4.5.0
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-library
