global:
  suspend: false
tjeneste:
  version: r4.4.0-py311-2025.12.04T14_04Z
  image:
    pullPolicy: IfNotPresent
security:
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
  serviceEntry:
    enabled: true
    hosts:
      - storage.googleapis.com
  oauth2:
    provider: keycloak-oidc
    oidcIssuerUrl: overwritten-by-onyxia
    clientId: my-client
    authenticatedEmails: ''
init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
environment:
  user: onyxia
  group: users
userAttributes:
  environmentVariableName: OIDC_TOKEN
  userAttribute: access_token
  value: ''
dapla:
  sourceData:
    reason: ''
    requestedDuration: 4h
  group: ''
  sharedBuckets: []
gitConfig:
  git:
    enabled: false
    configMapName: ''
    name: ''
    email: ''
    cache: ''
  github:
    token: ''
    repository: ''
    branch: ''
    build: false
oidc:
  enabled: true
  tokenExchangeUrl: ''
  configMapName: ''
repository:
  configMapName: ''
  pipRepository: ''
  condaRepository: ''
discovery:
  mlflow: true
mlflow:
  configMapName: ''
replicaCount: 1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
kubernetes:
  enabled: false
podAnnotations: {}
podLabels:
  onyxia.app: jupyterlab
podSecurityContext:
  fsGroup: 100
securityContext: {}
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8888
  sparkui:
    port: 4040
istio:
  enabled: false
  gateways:
    - istio-namespace/example-gateway
  hostname: chart-example.local
resources:
  cpu: ''
  memory: ''
diskplass:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
avansert:
  data:
    mountStandard: true
  startupScript:
    scriptPath: ''
    scriptArgs: ''
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
deleteJob:
  enabled: true
  cronMinuteAtDay: '0'
  cronHourAtDay: '20'
  imageVersion: v1.1.0
  clusterRoleName: onyxia-delete-job
  serviceAccount:
    annotations: {}
podDisruptionBudget:
  enabled: true
deployEnvironment: DEV
daplaUser: ''
statbankBaseUrl: ''
statbankEncryptUrl: ''
statbankTestBaseUrl: ''
statbankTestEncryptUrl: ''
maskinportenGuardianUrl: ''
